// Generated by CoffeeScript 1.8.0
(function() {
  angular.module('app').factory('leaderboardService', [
    '$log', '$http', '$q', 'UserService', function($log, $http, $q, userService) {
      var self;
      self = {};
      self.get = function() {
        return $http.get('/api/leaderboard');
      };
      return self;
    }
  ]);

}).call(this);
